import { DataFile, Nuance } from "../types/types";

export const NUANCES: Nuance[] = [
    {
        libelle: "Gauche",
        codesMinistere: [
            "EXG",
            "COM",
            "FI",
            "SOC",
            "RDG",
            "UG",
            "VEC",
            "DVG",
            "ECO",
            "NUP",
            "DXG",
        ],
        couleur: "#e41c1f",
        nombreQualifies: 0,
    },
    {
        libelle: "Centre droit",
        codesMinistere: ["REN", "ENS", "MOD", "HOR", "DVC", "UDI"],
        couleur: "#fdd00b",
        nombreQualifies: 0,
    },
    {
        libelle: "Droite",
        codesMinistere: ["LR", "DVD"],
        couleur: "#1175ff",
        nombreQualifies: 0,
    },
    {
        libelle: "Extreme droite",
        codesMinistere: ["DSV", "RN", "REC", "EXD", "UXD"],
        couleur: "#0c2a6b",
        nombreQualifies: 0,
    },
    {
        libelle: "Autres",
        codesMinistere: ["REG", "DIV"],
        couleur: "#b7b7b7",
        nombreQualifies: 0,
    },
];

// URL du ministère de l'Intérieur
// const URL =
//     "https://www.resultats-elections.interieur.gouv.fr/telechargements/LG2024/resultatsT1";

// URL du jeu de test local
const URL = "data";

export const FILES: DataFile[] = [
    { url: `${URL}/01/R101CIR.xml`, fetched: false },
    { url: `${URL}/02/R102CIR.xml`, fetched: false },
    { url: `${URL}/03/R103CIR.xml`, fetched: false },
    { url: `${URL}/04/R104CIR.xml`, fetched: false },
    { url: `${URL}/05/R105CIR.xml`, fetched: false },
    { url: `${URL}/06/R106CIR.xml`, fetched: false },
    { url: `${URL}/07/R107CIR.xml`, fetched: false },
    { url: `${URL}/08/R108CIR.xml`, fetched: false },
    { url: `${URL}/09/R109CIR.xml`, fetched: false },
    { url: `${URL}/10/R110CIR.xml`, fetched: false },
    { url: `${URL}/11/R111CIR.xml`, fetched: false },
    { url: `${URL}/12/R112CIR.xml`, fetched: false },
    { url: `${URL}/13/R113CIR.xml`, fetched: false },
    { url: `${URL}/14/R114CIR.xml`, fetched: false },
    { url: `${URL}/15/R115CIR.xml`, fetched: false },
    { url: `${URL}/16/R116CIR.xml`, fetched: false },
    { url: `${URL}/17/R117CIR.xml`, fetched: false },
    { url: `${URL}/18/R118CIR.xml`, fetched: false },
    { url: `${URL}/19/R119CIR.xml`, fetched: false },
    { url: `${URL}/2A/R12ACIR.xml`, fetched: false },
    { url: `${URL}/2B/R12BCIR.xml`, fetched: false },
    { url: `${URL}/21/R121CIR.xml`, fetched: false },
    { url: `${URL}/22/R122CIR.xml`, fetched: false },
    { url: `${URL}/23/R123CIR.xml`, fetched: false },
    { url: `${URL}/24/R124CIR.xml`, fetched: false },
    { url: `${URL}/25/R125CIR.xml`, fetched: false },
    { url: `${URL}/26/R126CIR.xml`, fetched: false },
    { url: `${URL}/27/R127CIR.xml`, fetched: false },
    { url: `${URL}/28/R128CIR.xml`, fetched: false },
    { url: `${URL}/29/R129CIR.xml`, fetched: false },
    { url: `${URL}/30/R130CIR.xml`, fetched: false },
    { url: `${URL}/31/R131CIR.xml`, fetched: false },
    { url: `${URL}/32/R132CIR.xml`, fetched: false },
    { url: `${URL}/33/R133CIR.xml`, fetched: false },
    { url: `${URL}/34/R134CIR.xml`, fetched: false },
    { url: `${URL}/35/R135CIR.xml`, fetched: false },
    { url: `${URL}/36/R136CIR.xml`, fetched: false },
    { url: `${URL}/37/R137CIR.xml`, fetched: false },
    { url: `${URL}/38/R138CIR.xml`, fetched: false },
    { url: `${URL}/39/R139CIR.xml`, fetched: false },
    { url: `${URL}/40/R140CIR.xml`, fetched: false },
    { url: `${URL}/41/R141CIR.xml`, fetched: false },
    { url: `${URL}/42/R142CIR.xml`, fetched: false },
    { url: `${URL}/43/R143CIR.xml`, fetched: false },
    { url: `${URL}/44/R144CIR.xml`, fetched: false },
    { url: `${URL}/45/R145CIR.xml`, fetched: false },
    { url: `${URL}/46/R146CIR.xml`, fetched: false },
    { url: `${URL}/47/R147CIR.xml`, fetched: false },
    { url: `${URL}/48/R148CIR.xml`, fetched: false },
    { url: `${URL}/49/R149CIR.xml`, fetched: false },
    { url: `${URL}/50/R150CIR.xml`, fetched: false },
    { url: `${URL}/51/R151CIR.xml`, fetched: false },
    { url: `${URL}/52/R152CIR.xml`, fetched: false },
    { url: `${URL}/53/R153CIR.xml`, fetched: false },
    { url: `${URL}/54/R154CIR.xml`, fetched: false },
    { url: `${URL}/55/R155CIR.xml`, fetched: false },
    { url: `${URL}/56/R156CIR.xml`, fetched: false },
    { url: `${URL}/57/R157CIR.xml`, fetched: false },
    { url: `${URL}/58/R158CIR.xml`, fetched: false },
    { url: `${URL}/59/R159CIR.xml`, fetched: false },
    { url: `${URL}/60/R160CIR.xml`, fetched: false },
    { url: `${URL}/61/R161CIR.xml`, fetched: false },
    { url: `${URL}/62/R162CIR.xml`, fetched: false },
    { url: `${URL}/63/R163CIR.xml`, fetched: false },
    { url: `${URL}/64/R164CIR.xml`, fetched: false },
    { url: `${URL}/65/R165CIR.xml`, fetched: false },
    { url: `${URL}/66/R166CIR.xml`, fetched: false },
    { url: `${URL}/67/R167CIR.xml`, fetched: false },
    { url: `${URL}/68/R168CIR.xml`, fetched: false },
    { url: `${URL}/69/R169CIR.xml`, fetched: false },
    { url: `${URL}/70/R170CIR.xml`, fetched: false },
    { url: `${URL}/71/R171CIR.xml`, fetched: false },
    { url: `${URL}/72/R172CIR.xml`, fetched: false },
    { url: `${URL}/73/R173CIR.xml`, fetched: false },
    { url: `${URL}/74/R174CIR.xml`, fetched: false },
    { url: `${URL}/75/R175CIR.xml`, fetched: false },
    { url: `${URL}/76/R176CIR.xml`, fetched: false },
    { url: `${URL}/77/R177CIR.xml`, fetched: false },
    { url: `${URL}/78/R178CIR.xml`, fetched: false },
    { url: `${URL}/79/R179CIR.xml`, fetched: false },
    { url: `${URL}/80/R180CIR.xml`, fetched: false },
    { url: `${URL}/81/R181CIR.xml`, fetched: false },
    { url: `${URL}/82/R182CIR.xml`, fetched: false },
    { url: `${URL}/83/R183CIR.xml`, fetched: false },
    { url: `${URL}/84/R184CIR.xml`, fetched: false },
    { url: `${URL}/85/R185CIR.xml`, fetched: false },
    { url: `${URL}/86/R186CIR.xml`, fetched: false },
    { url: `${URL}/87/R187CIR.xml`, fetched: false },
    { url: `${URL}/88/R188CIR.xml`, fetched: false },
    { url: `${URL}/89/R189CIR.xml`, fetched: false },
    { url: `${URL}/90/R190CIR.xml`, fetched: false },
    { url: `${URL}/91/R191CIR.xml`, fetched: false },
    { url: `${URL}/92/R192CIR.xml`, fetched: false },
    { url: `${URL}/93/R193CIR.xml`, fetched: false },
    { url: `${URL}/94/R194CIR.xml`, fetched: false },
    { url: `${URL}/95/R195CIR.xml`, fetched: false },
    { url: `${URL}/971/R1971CIR.xml`, fetched: false },
    { url: `${URL}/972/R1972CIR.xml`, fetched: false },
    { url: `${URL}/973/R1973CIR.xml`, fetched: false },
    { url: `${URL}/974/R1974CIR.xml`, fetched: false },
    { url: `${URL}/975/R1975CIR.xml`, fetched: false },
    { url: `${URL}/976/R1976CIR.xml`, fetched: false },
    { url: `${URL}/986/R1986CIR.xml`, fetched: false },
    { url: `${URL}/987/R1987CIR.xml`, fetched: false },
    { url: `${URL}/988/R1988CIR.xml`, fetched: false },
    { url: `${URL}/ZX/R1ZXCIR.xml`, fetched: false },
    { url: `${URL}/ZZ/R1ZZCIR.xml`, fetched: false },
];
